language: scala

services:
  - rabbitmq

sudo: false

scala:
  - 2.13.1
  - 2.12.8
  # - 2.11.12

jdk:
  - openjdk11

# inspired by https://github.com/hashicorp/nomad-scala-sdk/blob/master/.travis.yml
matrix:
  exclude:

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
